apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nim-monitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nim-llm
  endpoints:
  - port: "8000"
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
